# Generated by Django 3.0.2 on 2020-02-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Camas',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('letra', models.CharField(db_column='LETRA', max_length=1)),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=45)),
                ('estado', models.CharField(db_column='ESTADO', max_length=45)),
            ],
            options={
                'db_table': 'camas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=45)),
                ('pago', models.FloatField(db_column='PAGO')),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=45)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(db_column='FECHA_REGISTRO')),
                ('fecha_cita', models.DateTimeField(db_column='FECHA_CITA')),
                ('asistio', models.IntegerField(blank=True, db_column='ASISTIO', null=True)),
                ('motivo', models.CharField(db_column='MOTIVO', max_length=45)),
            ],
            options={
                'db_table': 'citas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('dni', models.IntegerField(db_column='DNI', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=45)),
                ('apellidos', models.CharField(db_column='APELLIDOS', max_length=45)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=45)),
                ('direccion', models.CharField(db_column='DIRECCION', max_length=45)),
                ('fecha_ingreso', models.DateField(db_column='FECHA_INGRESO')),
                ('fecha_desp', models.DateField(blank=True, db_column='FECHA_DESP', null=True)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=45)),
                ('fecha_creacion', models.DateField(db_column='FECHA_CREACION')),
            ],
            options={
                'db_table': 'especialidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('numero', models.IntegerField(db_column='NUMERO')),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=45)),
            ],
            options={
                'db_table': 'habitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriasClinicas',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha_reg', models.DateTimeField(db_column='FECHA_REG')),
                ('peso', models.FloatField(db_column='PESO')),
                ('talla', models.FloatField(db_column='TALLA')),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=100)),
                ('imc', models.FloatField(blank=True, db_column='IMC', null=True)),
            ],
            options={
                'db_table': 'historias_clinicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=45)),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=45)),
            ],
            options={
                'db_table': 'medicamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('dni', models.IntegerField(db_column='DNI', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='NOMBRES', max_length=45)),
                ('apellidos', models.CharField(db_column='APELLIDOS', max_length=45)),
                ('direccion', models.CharField(db_column='DIRECCION', max_length=45)),
                ('celular', models.CharField(db_column='CELULAR', max_length=45)),
                ('fecha_registro', models.DateTimeField(db_column='FECHA_REGISTRO')),
            ],
            options={
                'db_table': 'medicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('dni', models.IntegerField(db_column='DNI', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='NOMBRES', max_length=45)),
                ('apellidos', models.CharField(db_column='APELLIDOS', max_length=45)),
                ('direccion', models.CharField(db_column='DIRECCION', max_length=45)),
                ('celular', models.CharField(db_column='CELULAR', max_length=9)),
                ('fecha_nac', models.DateField(db_column='FECHA_NAC')),
                ('edad', models.IntegerField(blank=True, db_column='EDAD', null=True)),
            ],
            options={
                'db_table': 'pacientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('monto', models.FloatField(db_column='MONTO')),
                ('fecha', models.DateTimeField(db_column='FECHA')),
            ],
            options={
                'db_table': 'pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pisos',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('numero', models.IntegerField(db_column='NUMERO')),
                ('numero_hab', models.IntegerField(db_column='NUMERO_HAB')),
                ('fecha_inau', models.DateField(db_column='FECHA_INAU')),
            ],
            options={
                'db_table': 'pisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quirofanos',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('letra', models.CharField(db_column='LETRA', max_length=1)),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=45)),
            ],
            options={
                'db_table': 'quirofanos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('field_descripcion', models.CharField(db_column=' DESCRIPCION', max_length=45)),
                ('f_registro', models.DateTimeField(db_column='F_REGISTRO')),
            ],
            options={
                'db_table': 'recetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=45)),
                ('precio', models.FloatField(db_column='PRECIO')),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=45)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('dia_turno', models.CharField(db_column='DIA_TURNO', max_length=15)),
                ('hora_inicio', models.TimeField(db_column='HORA_INICIO')),
                ('hora_fin', models.TimeField(db_column='HORA_FIN')),
                ('cupos', models.IntegerField(db_column='CUPOS')),
            ],
            options={
                'db_table': 'turnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('servicio', models.OneToOneField(db_column='SERVICIO_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appclinica1.Servicio')),
                ('fecha_registro', models.DateTimeField(db_column='FECHA_REGISTRO')),
                ('motivo', models.CharField(db_column='MOTIVO', max_length=45)),
            ],
            options={
                'db_table': 'consultas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Internamiento',
            fields=[
                ('fecha_inicio', models.DateTimeField(db_column='FECHA_INICIO')),
                ('fecha_fin', models.DateTimeField(db_column='FECHA_FIN')),
                ('motivo', models.CharField(db_column='MOTIVO', max_length=45)),
                ('servicio', models.OneToOneField(db_column='SERVICIO_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appclinica1.Servicio')),
            ],
            options={
                'db_table': 'internamiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intervenciones',
            fields=[
                ('fecha', models.DateTimeField(db_column='FECHA')),
                ('duracion', models.FloatField(db_column='DURACION')),
                ('servicio', models.OneToOneField(db_column='SERVICIO_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appclinica1.Servicio')),
            ],
            options={
                'db_table': 'intervenciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecetasMedicamentos',
            fields=[
                ('recetas', models.OneToOneField(db_column='recetas_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appclinica1.Recetas')),
                ('cantidad', models.IntegerField(db_column='CANTIDAD')),
                ('fecha_inicio', models.DateField(db_column='FECHA_INICIO')),
                ('fecha_fin', models.DateField(db_column='FECHA_FIN')),
                ('intervalos', models.IntegerField(db_column='INTERVALOS')),
            ],
            options={
                'db_table': 'recetas_medicamentos',
                'managed': False,
            },
        ),
    ]
